/**
 * NexusAgent Enterprise - AI Engineer Studio & Agent Publishing Wizard
 * Manage and maintain Copilot Agent Artifacts: Demo Videos, Input/Output Docs, Knowledge Base, and Versions
 */

import { StorageService } from '../storage.js';
import { AgentCategories, CopilotModels, ActivityActionTypes, UserRoles } from '../types.js';

export const AgentUploadWizard = {
  state: {
    step: 1,
    editingAgentId: null,
    formData: {
      name: '',
      slug: '',
      tagline: '',
      category: AgentCategories.DEVOPS,
      copilotModel: CopilotModels.SONNET,
      copilotChatHandle: '@my-agent',
      tags: 'Copilot, Enterprise',
      instructionsSnippet: '',
      
      // Demo Video Artifact
      demoTitle: 'VS Code Copilot Execution Demo',
      demoDuration: '1m 30s',
      demoVideoFile: null,
      demoSteps: [
        { time: '0:00', title: 'Open VS Code Copilot Chat', detail: 'Developer types prompt' },
        { time: '0:45', title: 'Agent injects Knowledge Base context', detail: 'Analyzes enterprise guidelines and generates solution' }
      ],

      // Input Documents
      inputDocs: [
        {
          title: 'Sample Input Payload / Log',
          filename: 'sample-input.log',
          fileType: 'LOG',
          size: '4.2 KB',
          description: 'Example input data for agent evaluation',
          content: '2026-08-15 [INFO] Initializing sample container service...\n[ERROR] Connection timeout to database cluster on port 5432'
        }
      ],

      // Output Documents
      outputDocs: [
        {
          title: 'Sample Output Code Patch',
          filename: 'fix-patch.diff',
          fileType: 'DIFF',
          size: '2.1 KB',
          description: 'Verified output generated by agent in VS Code',
          content: '+ const pool = new Pool({ max: 20, idleTimeoutMillis: 30000 });\n- const pool = new Pool();'
        }
      ],

      // Knowledge Base Articles
      kbArticles: [
        {
          id: 'kb-custom-1',
          title: 'Enterprise Architecture & Operations Runbook',
          category: 'Operations',
          author: 'AI Engineering Lead',
          lastUpdated: '2026-08-15',
          tokenCount: 3200,
          description: 'Production guidelines and error codes',
          content: '# Enterprise Operational Standards\n1. All database calls must declare explicit connection timeouts.\n2. Ingress controllers must adhere to zero-trust TLS 1.3.'
        }
      ],

      architectureDiagram: {
        title: 'System Architecture Overview',
        caption: 'High-level view of the agent system interactions and integrations.',
        attachment: null,
        dataUrl: ''
      },

      // Versioning
      version: '1.0.0',
      changelog: 'Initial enterprise release with complete artifacts and VS Code Copilot integration.'
    }
  },

  open(agentId = null) {
    this.state.step = 1;
    this.state.editingAgentId = agentId;

    if (agentId) {
      const existing = StorageService.getAgentById(agentId);
      if (existing) {
        this.state.formData = {
          name: existing.name,
          slug: existing.slug,
          tagline: existing.tagline,
          category: existing.category,
          copilotModel: existing.copilotModel,
          copilotChatHandle: existing.copilotChatHandle,
          tags: existing.tags.join(', '),
          instructionsSnippet: existing.copilotConfig?.instructionsSnippet || '',
          demoTitle: existing.artifacts?.demoVideo?.title || 'VS Code Demo',
          demoDuration: existing.artifacts?.demoVideo?.duration || '1m 30s',
          demoSteps: existing.artifacts?.demoVideo?.simulatedTimeline || [],
          inputDocs: existing.artifacts?.inputDocuments || [],
          outputDocs: existing.artifacts?.outputDocuments || [],
          kbArticles: existing.artifacts?.knowledgeBase || [],
          architectureDiagram: {
            title: existing.architectureDiagram?.title || 'System Architecture Overview',
            caption: existing.architectureDiagram?.caption || 'High-level view of the agent system interactions and integrations.',
            attachment: existing.architectureDiagram?.attachment || null,
            dataUrl: existing.architectureDiagram?.url || ''
          },
          version: existing.version,
          changelog: 'Artifact update & version maintenance.'
        };
      }
    }
    this.render();
  },

  setStep(step) {
    this.state.step = step;
    this.render();
  },

  close() {
    // Reset wizard state to initial values
    this.state.step = 1;
    this.state.editingAgentId = null;
    this.state.formData = {
      name: '',
      slug: '',
      tagline: '',
      category: AgentCategories.DEVOPS,
      copilotModel: CopilotModels.SONNET,
      copilotChatHandle: '@my-agent',
      tags: 'Copilot, Enterprise',
      instructionsSnippet: '',
      demoTitle: 'VS Code Copilot Execution Demo',
      demoDuration: '1m 30s',
      demoVideoFile: null,
      demoSteps: [
        { time: '0:00', title: 'Open VS Code Copilot Chat', detail: 'Developer types prompt' },
        { time: '0:45', title: 'Agent injects Knowledge Base context', detail: 'Analyzes enterprise guidelines and generates solution' }
      ],
      inputDocs: [{
        title: 'Sample Input Payload / Log',
        filename: 'sample-input.log',
        fileType: 'LOG',
        size: '4.2 KB',
        description: 'Example input data for agent evaluation',
        content: '2026-08-15 [INFO] Initializing sample container service...\n[ERROR] Connection timeout to database cluster on port 5432'
      }],
      outputDocs: [{
        title: 'Sample Output Code Patch',
        filename: 'fix-patch.diff',
        fileType: 'DIFF',
        size: '2.1 KB',
        description: 'Verified output generated by agent in VS Code',
        content: '+ const pool = new Pool({ max: 20, idleTimeoutMillis: 30000 });\n- const pool = new Pool();'
      }],
      kbArticles: [{
        id: 'kb-custom-1',
        title: 'Enterprise Architecture & Operations Runbook',
        category: 'Operations',
        author: 'AI Engineering Lead',
        lastUpdated: '2026-08-15',
        tokenCount: 3200,
        description: 'Production guidelines and error codes',
        content: '# Enterprise Operational Standards\n1. All database calls must declare explicit connection timeouts.\n2. Ingress controllers must adhere to zero-trust TLS 1.3.'
      }],
      architectureDiagram: {
        title: 'System Architecture Overview',
        caption: 'High-level view of the agent system interactions and integrations.',
        attachment: null,
        dataUrl: ''
      },
      version: '1.0.0',
      changelog: 'Initial enterprise release with complete artifacts and VS Code Copilot integration.'
    };
    // Switch back to catalog tab
    window.NexusApp.navigate('catalog');
  },

  async attachArchitectureDiagramFile(file) {
    if (!file) return;

    const payload = await this.readFilePayload(file);
    const isImage = file.type.startsWith('image/') || /\.(png|jpg|jpeg|gif|svg|webp)$/i.test(file.name);

    let dataUrl = '';
    if (isImage) {
      dataUrl = await new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = (event) => resolve(typeof event.target.result === 'string' ? event.target.result : '');
        reader.onerror = () => reject(new Error(`Unable to read image: ${file.name}`));
        reader.readAsDataURL(file);
      });
    }

    this.state.formData.architectureDiagram = {
      title: this.state.formData.architectureDiagram?.title || file.name.replace(/\.[^.]+$/, ''),
      caption: this.state.formData.architectureDiagram?.caption || 'System architecture overview',
      attachment: {
        name: file.name,
        size: file.size,
        type: file.type || 'application/octet-stream',
        fileType: payload?.fileType || 'IMAGE',
        content: dataUrl || payload?.content || ''
      },
      dataUrl
    };

    this.render();
  },

  removeArchitectureDiagram() {
    this.state.formData.architectureDiagram = {
      title: 'System Architecture Overview',
      caption: 'High-level view of the agent system interactions and integrations.',
      attachment: null,
      dataUrl: ''
    };
    this.render();
  },

  addInputDoc() {
    this.state.formData.inputDocs.push({
      title: 'New Input Document',
      filename: 'input-data.json',
      fileType: 'JSON',
      size: '2.5 KB',
      description: 'Sample input schema',
      content: '{\n  "status": "sample_input",\n  "code": 200\n}'
    });
    this.render();
  },

  addOutputDoc() {
    this.state.formData.outputDocs.push({
      title: 'New Output Artifact',
      filename: 'output-code.ts',
      fileType: 'TYPESCRIPT',
      size: '3.0 KB',
      description: 'Sample generated code',
      content: '// Generated output\nexport function example() { return true; }'
    });
    this.render();
  },

  addKbArticle() {
    this.state.formData.kbArticles.push({
      id: `kb-${Date.now()}`,
      title: 'New Knowledge Base Guideline',
      category: 'Guidelines',
      author: 'AI Engineering Team',
      lastUpdated: new Date().toISOString().split('T')[0],
      tokenCount: 2400,
      description: 'Standard operating rules',
      content: '# Knowledge Base Document\n- Standard rule 1\n- Standard rule 2',
      attachment: null
    });
    this.render();
  },

  removeInputDoc(index) {
    this.state.formData.inputDocs.splice(index, 1);
    this.render();
  },

  removeOutputDoc(index) {
    this.state.formData.outputDocs.splice(index, 1);
    this.render();
  },

  removeKbArticle(index) {
    this.state.formData.kbArticles.splice(index, 1);
    this.render();
  },

  formatFileSize(bytes = 0) {
    if (!bytes) return '0 B';
    const units = ['B', 'KB', 'MB', 'GB'];
    const size = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1);
    const value = bytes / (1024 ** size);
    return `${value.toFixed(value >= 10 || size === 0 ? 0 : 1)} ${units[size]}`;
  },

  detectFileType(filename = '', mimeType = '') {
    const extension = (filename.split('.').pop() || '').toUpperCase();
    if (['JSON', 'LOG', 'MD', 'TXT', 'YAML', 'YML', 'CSV', 'DIFF', 'TS', 'JS', 'HTML', 'CSS', 'XML', 'SQL', 'PY', 'SH'].includes(extension)) {
      return extension;
    }
    if (mimeType.startsWith('image/')) return 'IMAGE';
    if (mimeType.startsWith('video/')) return 'VIDEO';
    if (mimeType.startsWith('audio/')) return 'AUDIO';
    return extension || 'FILE';
  },

  async readFilePayload(file) {
    if (!file) return null;

    const fileType = this.detectFileType(file.name, file.type || '');
    const isTextLike = file.type.startsWith('text/') || /\.(json|log|md|txt|yaml|yml|csv|diff|ts|js|html|css|xml|sql|py|sh)$/i.test(file.name);

    let content = '';
    if (isTextLike) {
      content = await new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = (event) => resolve(typeof event.target.result === 'string' ? event.target.result : '');
        reader.onerror = () => reject(new Error(`Unable to read file: ${file.name}`));
        reader.readAsText(file);
      });
    }

    return {
      name: file.name,
      size: this.formatFileSize(file.size),
      type: file.type || 'application/octet-stream',
      fileType,
      content
    };
  },

  async attachDemoVideoFile(file) {
    if (!file) return;

    const payload = await this.readFilePayload(file);
    this.state.formData.demoVideoFile = payload;
    this.state.formData.demoTitle = this.state.formData.demoTitle || file.name.replace(/\.[^.]+$/, '');
    this.render();
  },

  async attachCollectionFile(collectionKey, index, file) {
    if (!file || !this.state.formData[collectionKey]) return;

    const source = this.state.formData[collectionKey][index];
    const payload = await this.readFilePayload(file);
    this.state.formData[collectionKey][index] = {
      ...source,
      title: source.title || file.name.replace(/\.[^.]+$/, ''),
      filename: file.name,
      fileType: payload?.fileType || source.fileType || 'FILE',
      size: payload?.size || source.size || '0 B',
      description: source.description || `${file.name} uploaded for this artifact section.`,
      content: payload?.content || source.content || '',
      attachment: {
        name: payload?.name || file.name,
        size: file.size,
        type: payload?.type || file.type || 'application/octet-stream',
        fileType: payload?.fileType || 'FILE'
      }
    };

    this.render();
  },

  async attachKbArticleFile(index, file) {
    if (!file || !this.state.formData.kbArticles[index]) return;

    const source = this.state.formData.kbArticles[index];
    const payload = await this.readFilePayload(file);
    this.state.formData.kbArticles[index] = {
      ...source,
      title: source.title || file.name.replace(/\.[^.]+$/, ''),
      category: source.category || 'Uploaded Guide',
      description: source.description || `Attached reference file: ${file.name}`,
      content: payload?.content || source.content || '',
      attachment: {
        name: payload?.name || file.name,
        size: file.size,
        type: payload?.type || file.type || 'application/octet-stream',
        fileType: payload?.fileType || 'FILE'
      }
    };

    this.render();
  },

  publishAgent() {
    const f = this.state.formData;
    const isEdit = !!this.state.editingAgentId;
    const hasInputDocs = Array.isArray(f.inputDocs) && f.inputDocs.length > 0;
    const hasOutputDocs = Array.isArray(f.outputDocs) && f.outputDocs.length > 0;
    const certificationStatus = hasInputDocs && hasOutputDocs ? 'CERTIFIED' : 'IN_PROGRESS';
    const architectureDiagram = f.architectureDiagram || {};

    const agentPayload = {
      id: this.state.editingAgentId || `agent-${Date.now()}`,
      name: f.name || 'Custom Copilot Agent',
      slug: f.slug || (f.name ? f.name.toLowerCase().replace(/[^a-z0-9]/g, '-') : 'copilot-agent'),
      tagline: f.tagline || 'Enterprise GitHub Copilot agent for VS Code.',
      category: f.category,
      icon: 'cpu',
      color: '#8957e5',
      author: {
        name: 'Enterprise AI Engineer',
        role: 'AI Systems Architect',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
        team: 'AI Enablement Guild'
      },
      version: f.version || '1.0.0',
      copilotModel: f.copilotModel,
      copilotChatHandle: f.copilotChatHandle.startsWith('@') ? f.copilotChatHandle : `@${f.copilotChatHandle}`,
      tags: f.tags.split(',').map(t => t.trim()).filter(Boolean),
      architectureDiagram: {
        title: architectureDiagram.title || 'System Architecture Overview',
        caption: architectureDiagram.caption || 'System architecture overview',
        url: architectureDiagram.dataUrl || '',
        attachment: architectureDiagram.attachment ? {
          name: architectureDiagram.attachment.name,
          size: architectureDiagram.attachment.size,
          type: architectureDiagram.attachment.type,
          fileType: architectureDiagram.attachment.fileType,
          content: architectureDiagram.attachment.content || ''
        } : null
      },
      certificationStatus,
      lastUpdated: new Date().toISOString(),
      
      copilotConfig: {
        instructionsSnippet: f.instructionsSnippet || `# Custom Copilot Instructions\nYou are an enterprise AI assistant.`,
        promptFilePath: `.github/prompts/${f.slug || 'agent'}.prompt.md`
      },

      artifacts: {
        demoVideo: {
          title: f.demoTitle,
          duration: f.demoDuration,
          resolution: '1080p 60fps',
          simulatedTimeline: f.demoSteps,
          attachment: f.demoVideoFile ? {
            name: f.demoVideoFile.name,
            size: f.demoVideoFile.size,
            type: f.demoVideoFile.type,
            fileType: f.demoVideoFile.fileType,
            content: f.demoVideoFile.content || ''
          } : null
        },
        inputDocuments: f.inputDocs,
        outputDocuments: f.outputDocs,
        knowledgeBase: f.kbArticles
      },

      security: {
        scanStatus: 'PASSED',
        vulnerabilitiesDetected: 0,
        promptInjectionScore: '100% Resistant',
        piiMasking: 'ENABLED (Strict)',
        lastAudited: new Date().toISOString().split('T')[0]
      }
    };

    StorageService.saveAgent(agentPayload);
    StorageService.addAgentVersion(agentPayload.id, {
      version: agentPayload.version,
      author: 'Enterprise AI Engineer',
      changelog: f.changelog || 'Published updated agent artifacts and release notes.',
      instructionsDiff: `+ Updated agent metadata, Copilot instructions, and artifact bundles for version ${agentPayload.version}`
    });

    StorageService.logActivity(
      isEdit ? ActivityActionTypes.VERSION_BUMPED : ActivityActionTypes.AGENT_CREATED,
      'Enterprise AI Engineer',
      UserRoles.AI_ENGINEER,
      agentPayload.id,
      agentPayload.name,
      isEdit 
        ? `Updated agent artifacts and released version v${agentPayload.version}.`
        : `Published new GitHub Copilot agent with ${f.inputDocs.length} input docs, ${f.outputDocs.length} output docs, and ${f.kbArticles.length} KB articles.`,
      { version: agentPayload.version, category: agentPayload.category }
    );

    window.NexusApp.showToast(`Agent "${agentPayload.name}" v${agentPayload.version} published successfully!`, 'success');
    window.NexusApp.navigate('catalog');
  },

  render() {
    const container = document.getElementById('main-content');
    if (!container) return;

    const f = this.state.formData;
    const isEdit = !!this.state.editingAgentId;

    container.innerHTML = `
      <div class="space-y-6 max-w-4xl mx-auto animate-fadeIn">
        
        <!-- Header Banner with Close Button -->
        <div class="flex items-start justify-between bg-gradient-to-r from-[#1b1430] via-[#101935] to-[#0c1825] p-6 rounded-2xl border border-[var(--border-medium)] shadow-xl">
          <div class="space-y-1 flex-1">
            <div class="flex items-center gap-2">
              <span class="badge badge-purple text-xs"><i data-lucide="cpu" class="w-3.5 h-3.5"></i> AI Engineer Studio</span>
              <span class="badge badge-cyan text-xs">Artifact Maintenance & Versioning</span>
            </div>
            <h2 class="text-2xl font-extrabold text-white">
              ${isEdit ? `Maintain Agent Artifacts & Release v${f.version}` : 'Publish New GitHub Copilot Agent'}
            </h2>
            <p class="text-xs sm:text-sm text-[var(--text-secondary)]">
              Upload and maintain complete agent artifacts (Demo Videos, Input/Output docs, Knowledge Base runbooks) for VS Code Copilot.
            </p>
          </div>
          <button onclick="window.AgentUploadWizard.close()" class="p-2 rounded-xl text-[var(--text-muted)] hover:text-white hover:bg-[var(--bg-tertiary)] transition-colors">
            <i data-lucide="x" class="w-5 h-5"></i>
          </button>
        </div>

        <!-- Multi-Step Progress Stepper -->
        <div class="grid grid-cols-4 gap-2 bg-[var(--bg-tertiary)] p-2 rounded-xl border border-[var(--border-subtle)]">
          <button onclick="window.AgentUploadWizard.setStep(1)" class="p-2.5 rounded-lg text-xs font-semibold text-center transition-all ${this.state.step === 1 ? 'bg-purple-600 text-white shadow' : 'text-gray-400 hover:text-white'}">
            1. Metadata & Model
          </button>
          <button onclick="window.AgentUploadWizard.setStep(2)" class="p-2.5 rounded-lg text-xs font-semibold text-center transition-all ${this.state.step === 2 ? 'bg-purple-600 text-white shadow' : 'text-gray-400 hover:text-white'}">
            2. System Prompts
          </button>
          <button onclick="window.AgentUploadWizard.setStep(3)" class="p-2.5 rounded-lg text-xs font-semibold text-center transition-all ${this.state.step === 3 ? 'bg-purple-600 text-white shadow' : 'text-gray-400 hover:text-white'}">
            3. Artifacts & Demo
          </button>
          <button onclick="window.AgentUploadWizard.setStep(4)" class="p-2.5 rounded-lg text-xs font-semibold text-center transition-all ${this.state.step === 4 ? 'bg-purple-600 text-white shadow' : 'text-gray-400 hover:text-white'}">
            4. Knowledge Base & Release
          </button>
        </div>

        <!-- Step Content Panels -->
        <div class="glass-panel p-6 sm:p-8 rounded-2xl border border-[var(--border-medium)] space-y-6">
          
          <!-- STEP 1: METADATA & MODEL -->
          ${this.state.step === 1 ? `
            <div class="space-y-4 animate-fadeIn">
              <h3 class="text-base font-bold text-white flex items-center gap-2">
                <i data-lucide="info" class="w-4 h-4 text-purple-400"></i>
                Agent Identity & Copilot Model Configuration
              </h3>

              <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label class="block text-xs font-semibold text-gray-300 mb-1">Agent Name</label>
                  <input type="text" value="${f.name}" oninput="window.AgentUploadWizard.state.formData.name = this.value" placeholder="e.g. Next.js 19 Microfrontend Architect" class="input-field text-xs" />
                </div>
                <div>
                  <label class="block text-xs font-semibold text-gray-300 mb-1">Copilot Chat Handle</label>
                  <input type="text" value="${f.copilotChatHandle}" oninput="window.AgentUploadWizard.state.formData.copilotChatHandle = this.value" placeholder="@my-agent" class="input-field text-xs font-mono" />
                </div>
              </div>

              <div>
                <label class="block text-xs font-semibold text-gray-300 mb-1">Tagline & Summary</label>
                <input type="text" value="${f.tagline}" oninput="window.AgentUploadWizard.state.formData.tagline = this.value" placeholder="Brief 1-sentence value proposition" class="input-field text-xs" />
              </div>

              <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label class="block text-xs font-semibold text-gray-300 mb-1">Category</label>
                  <select onchange="window.AgentUploadWizard.state.formData.category = this.value" class="input-field text-xs">
                    ${Object.values(AgentCategories).map(cat => `
                      <option value="${cat}" ${f.category === cat ? 'selected' : ''}>${cat}</option>
                    `).join('')}
                  </select>
                </div>
                <div>
                  <label class="block text-xs font-semibold text-gray-300 mb-1">Approved GitHub Copilot Model</label>
                  <select onchange="window.AgentUploadWizard.state.formData.copilotModel = this.value" class="input-field text-xs">
                    ${Object.values(CopilotModels).map(m => `
                      <option value="${m}" ${f.copilotModel === m ? 'selected' : ''}>${m}</option>
                    `).join('')}
                  </select>
                </div>
              </div>

              <div>
                <label class="block text-xs font-semibold text-gray-300 mb-1">Tags (Comma-separated)</label>
                <input type="text" value="${f.tags}" oninput="window.AgentUploadWizard.state.formData.tags = this.value" placeholder="React 19, TypeScript, Performance" class="input-field text-xs" />
              </div>

              <div class="pt-4 border-t border-[var(--border-subtle)] flex justify-end">
                <button onclick="window.AgentUploadWizard.setStep(2)" class="btn btn-primary btn-sm flex items-center gap-1">
                  Next: System Prompts <i data-lucide="arrow-right" class="w-3.5 h-3.5"></i>
                </button>
              </div>
            </div>
          ` : ''}

          <!-- STEP 2: SYSTEM PROMPTS -->
          ${this.state.step === 2 ? `
            <div class="space-y-4 animate-fadeIn">
              <h3 class="text-base font-bold text-white flex items-center gap-2">
                <i data-lucide="file-code" class="w-4 h-4 text-cyan-400"></i>
                GitHub Copilot System Instructions (.github/copilot-instructions.md)
              </h3>
              <p class="text-xs text-[var(--text-secondary)]">These instructions will be compiled directly into the downloadable .vscode configuration and govern Copilot's response behavior.</p>

              <div>
                <label class="block text-xs font-semibold text-gray-300 mb-1">Copilot Instructions Content</label>
                <textarea 
                  rows="10" 
                  oninput="window.AgentUploadWizard.state.formData.instructionsSnippet = this.value"
                  placeholder="# GitHub Copilot Agent Instructions&#10;You are an expert...&#10;1. Enforce strict standards...&#10;2. Generate minimal verified code diffs." 
                  class="input-field font-mono text-xs"
                >${f.instructionsSnippet}</textarea>
              </div>

              <div class="pt-4 border-t border-[var(--border-subtle)] flex justify-between">
                <button onclick="window.AgentUploadWizard.setStep(1)" class="btn btn-secondary btn-sm flex items-center gap-1">
                  <i data-lucide="arrow-left" class="w-3.5 h-3.5"></i> Back
                </button>
                <button onclick="window.AgentUploadWizard.setStep(3)" class="btn btn-primary btn-sm flex items-center gap-1">
                  Next: Maintain Artifacts & Demo <i data-lucide="arrow-right" class="w-3.5 h-3.5"></i>
                </button>
              </div>
            </div>
          ` : ''}

          <!-- STEP 3: ARTIFACTS (DEMO VIDEO, INPUT / OUTPUT DOCUMENTS) -->
          ${this.state.step === 3 ? `
            <div class="space-y-6 animate-fadeIn">
              <div class="flex items-center justify-between">
                <div>
                  <h3 class="text-base font-bold text-white flex items-center gap-2">
                    <i data-lucide="layers" class="w-4 h-4 text-emerald-400"></i>
                    Agent Artifacts: Demo Walkthrough, Input & Output Documents
                  </h3>
                  <p class="text-xs text-[var(--text-secondary)]">Maintain real sample documents so developers can inspect verified behavior.</p>
                </div>
              </div>

              <!-- 1. Demo Video Metadata -->
              <div class="bg-[var(--bg-tertiary)] p-4 rounded-xl border border-[var(--border-subtle)] space-y-3">
                <div class="flex items-center justify-between gap-2">
                  <div class="text-xs font-bold uppercase text-purple-300 flex items-center gap-1.5">
                    <i data-lucide="video" class="w-4 h-4"></i> Demo Walkthrough Video
                  </div>
                  <label class="btn btn-secondary btn-sm py-1 px-2 text-[11px] flex items-center gap-1 cursor-pointer">
                    <i data-lucide="paperclip" class="w-3 h-3"></i> Attach File
                    <input type="file" class="hidden" onchange="window.AgentUploadWizard.attachDemoVideoFile(event.target.files[0])" />
                  </label>
                </div>
                <div class="grid grid-cols-2 gap-3">
                  <div>
                    <label class="block text-[11px] font-semibold text-gray-300 mb-1">Demo Title</label>
                    <input type="text" value="${f.demoTitle}" oninput="window.AgentUploadWizard.state.formData.demoTitle = this.value" class="input-field text-xs" />
                  </div>
                  <div>
                    <label class="block text-[11px] font-semibold text-gray-300 mb-1">Video Duration</label>
                    <input type="text" value="${f.demoDuration}" oninput="window.AgentUploadWizard.state.formData.demoDuration = this.value" class="input-field text-xs" />
                  </div>
                </div>
                ${f.demoVideoFile ? `
                  <div class="rounded-lg border border-cyan-500/30 bg-cyan-500/10 px-3 py-2 text-[11px] text-cyan-200 flex items-center justify-between gap-3">
                    <span><strong>Attached:</strong> ${f.demoVideoFile.name}</span>
                    <span class="text-cyan-300/80">${f.demoVideoFile.size}</span>
                  </div>
                ` : ''}
              </div>

              <!-- 2. Input Documents -->
              <div class="space-y-3">
                <div class="flex items-center justify-between">
                  <div class="text-xs font-bold uppercase text-cyan-300 flex items-center gap-1.5">
                    <i data-lucide="file-input" class="w-4 h-4"></i> Input Documents (${f.inputDocs.length})
                  </div>
                  <button onclick="window.AgentUploadWizard.addInputDoc()" class="btn btn-secondary btn-sm py-1 text-[11px] flex items-center gap-1">
                    <i data-lucide="plus" class="w-3 h-3"></i> Add Input Doc
                  </button>
                </div>

                ${f.inputDocs.map((doc, idx) => `
                  <div class="p-3 bg-[var(--bg-input)] rounded-xl border border-[var(--border-subtle)] space-y-2">
                    <div class="flex items-center justify-between gap-2">
                      <div class="grid grid-cols-2 gap-2 flex-1">
                        <input type="text" value="${doc.title}" oninput="window.AgentUploadWizard.state.formData.inputDocs[${idx}].title = this.value" placeholder="Doc Title" class="input-field py-1 text-xs" />
                        <input type="text" value="${doc.filename}" oninput="window.AgentUploadWizard.state.formData.inputDocs[${idx}].filename = this.value" placeholder="filename.log" class="input-field py-1 text-xs font-mono" />
                      </div>
                      <div class="flex items-center gap-2">
                        <label class="btn btn-secondary btn-xs px-2 py-1 text-[10px] flex items-center gap-1 cursor-pointer whitespace-nowrap">
                          <i data-lucide="paperclip" class="w-3 h-3"></i> Attach
                          <input type="file" class="hidden" onchange="window.AgentUploadWizard.attachCollectionFile('inputDocs', ${idx}, event.target.files[0])" />
                        </label>
                        <button type="button" onclick="window.AgentUploadWizard.removeInputDoc(${idx})" class="btn btn-danger btn-xs px-2 py-1 text-[10px] whitespace-nowrap">
                          Remove
                        </button>
                      </div>
                    </div>
                    ${doc.attachment ? `
                      <div class="text-[10px] text-cyan-200 bg-cyan-500/10 border border-cyan-500/25 rounded px-2 py-1 flex items-center justify-between gap-2">
                        <span>${doc.attachment.name}</span>
                        <span>${this.formatFileSize(doc.attachment.size)}</span>
                      </div>
                    ` : ''}
                    <textarea rows="3" oninput="window.AgentUploadWizard.state.formData.inputDocs[${idx}].content = this.value" class="input-field font-mono text-xs">${doc.content}</textarea>
                  </div>
                `).join('')}
              </div>

              <!-- 3. Output Documents -->
              <div class="space-y-3">
                <div class="flex items-center justify-between">
                  <div class="text-xs font-bold uppercase text-emerald-300 flex items-center gap-1.5">
                    <i data-lucide="file-output" class="w-4 h-4"></i> Output Documents (${f.outputDocs.length})
                  </div>
                  <button onclick="window.AgentUploadWizard.addOutputDoc()" class="btn btn-secondary btn-sm py-1 text-[11px] flex items-center gap-1">
                    <i data-lucide="plus" class="w-3 h-3"></i> Add Output Doc
                  </button>
                </div>

                ${f.outputDocs.map((doc, idx) => `
                  <div class="p-3 bg-[var(--bg-input)] rounded-xl border border-[var(--border-subtle)] space-y-2">
                    <div class="flex items-center justify-between gap-2">
                      <div class="grid grid-cols-2 gap-2 flex-1">
                        <input type="text" value="${doc.title}" oninput="window.AgentUploadWizard.state.formData.outputDocs[${idx}].title = this.value" placeholder="Doc Title" class="input-field py-1 text-xs" />
                        <input type="text" value="${doc.filename}" oninput="window.AgentUploadWizard.state.formData.outputDocs[${idx}].filename = this.value" placeholder="patch.diff" class="input-field py-1 text-xs font-mono" />
                      </div>
                      <div class="flex items-center gap-2">
                        <label class="btn btn-secondary btn-xs px-2 py-1 text-[10px] flex items-center gap-1 cursor-pointer whitespace-nowrap">
                          <i data-lucide="paperclip" class="w-3 h-3"></i> Attach
                          <input type="file" class="hidden" onchange="window.AgentUploadWizard.attachCollectionFile('outputDocs', ${idx}, event.target.files[0])" />
                        </label>
                        <button type="button" onclick="window.AgentUploadWizard.removeOutputDoc(${idx})" class="btn btn-danger btn-xs px-2 py-1 text-[10px] whitespace-nowrap">
                          Remove
                        </button>
                      </div>
                    </div>
                    ${doc.attachment ? `
                      <div class="text-[10px] text-emerald-200 bg-emerald-500/10 border border-emerald-500/25 rounded px-2 py-1 flex items-center justify-between gap-2">
                        <span>${doc.attachment.name}</span>
                        <span>${this.formatFileSize(doc.attachment.size)}</span>
                      </div>
                    ` : ''}
                    <textarea rows="3" oninput="window.AgentUploadWizard.state.formData.outputDocs[${idx}].content = this.value" class="input-field font-mono text-xs">${doc.content}</textarea>
                  </div>
                `).join('')}
              </div>

              <div class="pt-4 border-t border-[var(--border-subtle)] flex justify-between">
                <button onclick="window.AgentUploadWizard.setStep(2)" class="btn btn-secondary btn-sm flex items-center gap-1">
                  <i data-lucide="arrow-left" class="w-3.5 h-3.5"></i> Back
                </button>
                <button onclick="window.AgentUploadWizard.setStep(4)" class="btn btn-primary btn-sm flex items-center gap-1">
                  Next: Knowledge Base & Release <i data-lucide="arrow-right" class="w-3.5 h-3.5"></i>
                </button>
              </div>
            </div>
          ` : ''}

          <!-- STEP 4: KNOWLEDGE BASE & VERSION RELEASE -->
          ${this.state.step === 4 ? `
            <div class="space-y-6 animate-fadeIn">
              <div class="space-y-3">
                <div class="flex items-center justify-between">
                  <div class="text-xs font-bold uppercase text-amber-300 flex items-center gap-1.5">
                    <i data-lucide="book-open" class="w-4 h-4"></i> Knowledge Base Maintenance (${f.kbArticles.length} Guides)
                  </div>
                  <button onclick="window.AgentUploadWizard.addKbArticle()" class="btn btn-secondary btn-sm py-1 text-[11px] flex items-center gap-1">
                    <i data-lucide="plus" class="w-3 h-3"></i> Attach Runbook
                  </button>
                </div>

                ${f.kbArticles.map((kb, idx) => `
                  <div class="p-4 bg-[var(--bg-tertiary)] rounded-xl border border-[var(--border-subtle)] space-y-2">
                    <div class="flex items-center justify-between gap-2">
                      <div class="grid grid-cols-2 gap-2 flex-1">
                        <input type="text" value="${kb.title}" oninput="window.AgentUploadWizard.state.formData.kbArticles[${idx}].title = this.value" placeholder="Runbook Title" class="input-field py-1 text-xs" />
                        <input type="text" value="${kb.category}" oninput="window.AgentUploadWizard.state.formData.kbArticles[${idx}].category = this.value" placeholder="Category" class="input-field py-1 text-xs" />
                      </div>
                      <div class="flex items-center gap-2">
                        <label class="btn btn-secondary btn-xs px-2 py-1 text-[10px] flex items-center gap-1 cursor-pointer whitespace-nowrap">
                          <i data-lucide="paperclip" class="w-3 h-3"></i> Attach
                          <input type="file" class="hidden" onchange="window.AgentUploadWizard.attachKbArticleFile(${idx}, event.target.files[0])" />
                        </label>
                        <button type="button" onclick="window.AgentUploadWizard.removeKbArticle(${idx})" class="btn btn-danger btn-xs px-2 py-1 text-[10px] whitespace-nowrap">
                          Remove
                        </button>
                      </div>
                    </div>
                    ${kb.attachment ? `
                      <div class="text-[10px] text-amber-200 bg-amber-500/10 border border-amber-500/25 rounded px-2 py-1 flex items-center justify-between gap-2">
                        <span>${kb.attachment.name}</span>
                        <span>${this.formatFileSize(kb.attachment.size)}</span>
                      </div>
                    ` : ''}
                    <textarea rows="4" oninput="window.AgentUploadWizard.state.formData.kbArticles[${idx}].content = this.value" class="input-field font-mono text-xs">${kb.content}</textarea>
                  </div>
                `).join('')}
              </div>

              <div class="bg-[var(--bg-tertiary)] p-4 rounded-xl border border-[var(--border-subtle)] space-y-3">
                <div class="flex items-center justify-between gap-2">
                  <div class="text-xs font-bold uppercase text-amber-300 flex items-center gap-1.5">
                    <i data-lucide="workflow" class="w-4 h-4"></i> Architecture Diagram
                  </div>
                  <label class="btn btn-secondary btn-sm py-1 px-2 text-[11px] flex items-center gap-1 cursor-pointer">
                    <i data-lucide="paperclip" class="w-3 h-3"></i> Attach Image
                    <input type="file" accept="image/*" class="hidden" onchange="window.AgentUploadWizard.attachArchitectureDiagramFile(event.target.files[0])" />
                  </label>
                </div>

                <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  <div>
                    <label class="block text-[11px] font-semibold text-gray-300 mb-1">Diagram Title</label>
                    <input type="text" value="${f.architectureDiagram?.title || ''}" oninput="window.AgentUploadWizard.state.formData.architectureDiagram.title = this.value" class="input-field text-xs" />
                  </div>
                  <div>
                    <label class="block text-[11px] font-semibold text-gray-300 mb-1">Diagram Caption</label>
                    <input type="text" value="${f.architectureDiagram?.caption || ''}" oninput="window.AgentUploadWizard.state.formData.architectureDiagram.caption = this.value" class="input-field text-xs" />
                  </div>
                </div>

                ${f.architectureDiagram?.attachment ? `
                  <div class="text-[10px] text-amber-200 bg-amber-500/10 border border-amber-500/25 rounded px-2 py-1 flex items-center justify-between gap-2">
                    <span>${f.architectureDiagram.attachment.name}</span>
                    <span>${this.formatFileSize(f.architectureDiagram.attachment.size)}</span>
                  </div>
                ` : ''}

                ${f.architectureDiagram?.dataUrl ? `
                  <div class="rounded-lg overflow-hidden border border-[var(--border-medium)] bg-[var(--bg-input)] p-2">
                    <img src="${f.architectureDiagram.dataUrl}" alt="Architecture diagram preview" class="w-full max-h-64 object-contain rounded-md" />
                    <div class="mt-2 flex justify-end">
                      <button type="button" onclick="window.AgentUploadWizard.removeArchitectureDiagram()" class="btn btn-danger btn-xs px-2 py-1 text-[10px]">
                        Remove Diagram
                      </button>
                    </div>
                  </div>
                ` : ''}
              </div>

              <!-- Semantic Version Release Card -->
              <div class="bg-gradient-to-r from-purple-900/30 to-indigo-900/20 p-5 rounded-2xl border border-purple-500/40 space-y-3">
                <div class="text-xs font-bold uppercase text-purple-300 flex items-center gap-2">
                  <i data-lucide="git-branch" class="w-4 h-4"></i> Semantic Versioning & Release Lifecycle
                </div>

                <div class="grid grid-cols-1 sm:grid-cols-3 gap-3">
                  <div>
                    <label class="block text-[11px] font-semibold text-gray-300 mb-1">Target Version</label>
                    <input type="text" value="${f.version}" oninput="window.AgentUploadWizard.state.formData.version = this.value" placeholder="1.0.0" class="input-field text-xs font-mono font-bold text-cyan-300" />
                  </div>
                  <div class="sm:col-span-2">
                    <label class="block text-[11px] font-semibold text-gray-300 mb-1">Release Changelog Notes</label>
                    <input type="text" value="${f.changelog}" oninput="window.AgentUploadWizard.state.formData.changelog = this.value" placeholder="Summary of changes in this version" class="input-field text-xs" />
                  </div>
                </div>
              </div>

              <div class="pt-4 border-t border-[var(--border-subtle)] flex justify-between">
                <button onclick="window.AgentUploadWizard.setStep(3)" class="btn btn-secondary btn-sm flex items-center gap-1">
                  <i data-lucide="arrow-left" class="w-3.5 h-3.5"></i> Back
                </button>
                <button onclick="window.AgentUploadWizard.publishAgent()" class="btn btn-primary btn-sm px-6 flex items-center gap-2 shadow-lg shadow-purple-600/30">
                  <i data-lucide="check-circle" class="w-4 h-4"></i>
                  <span>Publish to Enterprise Store</span>
                </button>
              </div>
            </div>
          ` : ''}

        </div>

      </div>
    `;

    if (window.lucide) window.lucide.createIcons();
  }
};
