/**
 * NexusAgent Enterprise - Interactive Copilot Sandbox Playground
 * Test run Copilot agents with simulated context injection, knowledge retrieval, and live token metrics
 */

import { StorageService } from '../storage.js';
import { ActivityActionTypes } from '../types.js';

export const InteractivePlayground = {
  state: {
    selectedAgentId: 'agent-sre-k8s',
    chatHistory: [],
    isExecuting: false,
    selectedModel: 'claude-3.5-sonnet',
    includeKnowledgeBase: true
  },

  selectAgent(id) {
    this.state.selectedAgentId = id;
    this.state.chatHistory = [];
    this.render();
  },

  sendSampleQuery(query) {
    const inputEl = document.getElementById('playground-input');
    if (inputEl) {
      inputEl.value = query;
      this.handleSend();
    }
  },

  async handleSend() {
    const inputEl = document.getElementById('playground-input');
    if (!inputEl || !inputEl.value.trim() || this.state.isExecuting) return;

    const userPrompt = inputEl.value.trim();
    inputEl.value = '';

    const agent = StorageService.getAgentById(this.state.selectedAgentId);
    if (!agent) return;

    // Add User Message
    this.state.chatHistory.push({
      role: 'user',
      content: userPrompt,
      timestamp: new Date().toLocaleTimeString()
    });

    this.state.isExecuting = true;
    this.renderChatOnly();

    // Log Activity
    StorageService.logActivity(
      ActivityActionTypes.SANDBOX_EXECUTED,
      'Enterprise Developer',
      'developer',
      agent.id,
      agent.name,
      `Executed prompt in interactive Copilot sandbox: "${userPrompt.substring(0, 60)}..."`,
      { model: this.state.selectedModel }
    );

    // Simulate Agent Thinking & Generating Response
    setTimeout(() => {
      let agentResponse = '';
      let generatedDiff = '';

      if (agent.id === 'agent-sre-k8s') {
        agentResponse = `### 🔍 Incident Root Cause Identified
Based on the provided Kubernetes crash logs and Prometheus metrics:
- **Root Cause**: The Pod \`checkout-service\` was terminated with **OOMKilled (Exit Code 137)** because the JVM heap allocation exceeded the container's 512Mi cgroup limit.
- **Knowledge Base Injected**: *Enterprise Kubernetes Production Runbook v3.2* (Enforcing \`-XX:MaxRAMPercentage\` and explicit 2Gi limits).

### 🛠️ Recommended YAML Patch Diff:`;
        generatedDiff = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service
spec:
  replicas: 4
  template:
    spec:
      containers:
      - name: checkout-app
        resources:
          requests:
            memory: "1024Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "1500m"
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:MaxRAMPercentage=80.0 -XX:+UseG1GC"`;
      } else if (agent.id === 'agent-secops-cve') {
        agentResponse = `### 🛡️ Vulnerability Analysis & Hardening
- **Flaw Detected**: CWE-89 (SQL Injection) in user authentication query.
- **Remediation**: Implemented strict parameterized query binding with Zod input email schema validation compliant with *OWASP Enterprise Standard 2026*.`;
        generatedDiff = `// Parameterized Query with Zod Validation
const emailSchema = z.string().email().max(255);
const validatedEmail = emailSchema.parse(req.body.email);

const user = await db('users')
  .where({ email: validatedEmail, tenant_id: req.tenantId })
  .first();`;
      } else {
        agentResponse = `### ⚡ Copilot Agent Response
Executed with model \`${this.state.selectedModel}\` under enterprise constraints.
- **System Instructions**: Active
- **Knowledge Base Documents**: Injected into context window
- **Validation**: 0 SAST warnings`;
        generatedDiff = `// Output generated by ${agent.name}
export async function enterpriseOptimizedHandler(context) {
  return await processWithCopilot(context);
}`;
      }

      this.state.chatHistory.push({
        role: 'agent',
        handle: agent.copilotChatHandle,
        content: agentResponse,
        diff: generatedDiff,
        metrics: {
          latency: `${(Math.random() * 0.6 + 0.8).toFixed(2)}s`,
          tokens: Math.floor(Math.random() * 400 + 650),
          guardrails: 'PASSED (0 Violations)'
        },
        timestamp: new Date().toLocaleTimeString()
      });

      this.state.isExecuting = false;
      this.render();
    }, 1200);
  },

  renderChatOnly() {
    const container = document.getElementById('chat-messages-container');
    if (!container) return;

    const agent = StorageService.getAgentById(this.state.selectedAgentId);

    container.innerHTML = `
      ${this.state.chatHistory.map(msg => this.renderMessage(msg, agent)).join('')}
      ${this.state.isExecuting ? `
        <div class="flex items-start gap-3 p-4 rounded-xl bg-[var(--bg-tertiary)] border border-purple-500/30 animate-pulse">
          <div class="w-8 h-8 rounded-lg bg-purple-600 flex items-center justify-center text-white">
            <i data-lucide="bot" class="w-4 h-4"></i>
          </div>
          <div class="space-y-1">
            <div class="text-xs font-bold text-purple-300 flex items-center gap-2">
              <span>${agent?.copilotChatHandle || '@copilot'}</span>
              <span class="text-[10px] text-gray-400">is analyzing logs & injecting knowledge base...</span>
            </div>
            <div class="text-xs text-gray-300">Evaluating prompt constraints and generating verified patch...</div>
          </div>
        </div>
      ` : ''}
    `;

    container.scrollTop = container.scrollHeight;
    if (window.lucide) window.lucide.createIcons();
  },

  renderMessage(msg, agent) {
    if (msg.role === 'user') {
      return `
        <div class="flex items-start gap-3 justify-end">
          <div class="bg-purple-900/40 border border-purple-500/40 p-4 rounded-2xl rounded-tr-none max-w-xl text-xs space-y-1">
            <div class="flex items-center justify-between gap-4 text-[10px] text-purple-300">
              <span class="font-bold">You (Developer)</span>
              <span>${msg.timestamp}</span>
            </div>
            <p class="text-white leading-relaxed whitespace-pre-wrap">${this.escapeHtml(msg.content)}</p>
          </div>
          <div class="w-8 h-8 rounded-lg bg-[var(--bg-tertiary)] border border-[var(--border-medium)] flex items-center justify-center text-gray-300 shrink-0">
            <i data-lucide="user" class="w-4 h-4"></i>
          </div>
        </div>
      `;
    }

    return `
      <div class="flex items-start gap-3">
        <div class="w-8 h-8 rounded-lg bg-gradient-to-tr from-purple-600 to-indigo-600 flex items-center justify-center text-white shrink-0 shadow-md">
          <i data-lucide="bot" class="w-4 h-4"></i>
        </div>
        <div class="bg-[var(--bg-card)] border border-[var(--border-medium)] p-4 rounded-2xl rounded-tl-none max-w-2xl text-xs space-y-3 shadow-lg">
          <div class="flex items-center justify-between gap-4 border-b border-[var(--border-subtle)] pb-2">
            <div class="flex items-center gap-2">
              <span class="font-bold text-white">${msg.handle || agent?.name}</span>
              <span class="badge badge-purple text-[9px]">GitHub Copilot</span>
            </div>
            <span class="text-[10px] text-[var(--text-muted)]">${msg.timestamp}</span>
          </div>

          <div class="text-gray-200 leading-relaxed space-y-2">
            ${msg.content.replace(/### (.*)/g, '<h4 class="font-bold text-white text-xs mt-2 mb-1">$1</h4>')}
          </div>

          ${msg.diff ? `
            <div class="space-y-1">
              <div class="flex items-center justify-between text-[10px] text-emerald-400 font-mono">
                <span>Output Code / Patch</span>
                <button onclick="navigator.clipboard.writeText(\`${msg.diff}\`); window.NexusApp.showToast('Copied code to clipboard!', 'success')" class="text-gray-400 hover:text-white flex items-center gap-1">
                  <i data-lucide="copy" class="w-3 h-3"></i> Copy
                </button>
              </div>
              <pre class="code-block text-[11px] max-h-56"><code>${this.escapeHtml(msg.diff)}</code></pre>
            </div>
          ` : ''}

          ${msg.metrics ? `
            <div class="flex items-center gap-4 text-[10px] text-[var(--text-muted)] pt-2 border-t border-[var(--border-subtle)]">
              <span>Latency: <strong class="text-cyan-400">${msg.metrics.latency}</strong></span>
              <span>Tokens: <strong class="text-purple-300">${msg.metrics.tokens}</strong></span>
              <span>Safety: <strong class="text-emerald-400">${msg.metrics.guardrails}</strong></span>
            </div>
          ` : ''}
        </div>
      </div>
    `;
  },

  render() {
    const container = document.getElementById('main-content');
    if (!container) return;

    const agents = StorageService.getAgents();
    const activeAgent = agents.find(a => a.id === this.state.selectedAgentId) || agents[0];
    const kbCount = activeAgent?.artifacts?.knowledgeBase?.length || 0;

    container.innerHTML = `
      <div class="space-y-6 animate-fadeIn">
        
        <!-- Top Title Bar -->
        <div class="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 bg-gradient-to-r from-[#17132a] via-[#101935] to-[#0c1825] p-6 rounded-2xl border border-[var(--border-medium)] shadow-xl">
          <div class="space-y-1">
            <div class="flex items-center gap-2">
              <span class="badge badge-cyan text-xs"><i data-lucide="terminal" class="w-3.5 h-3.5"></i> Interactive Execution</span>
              <span class="badge badge-purple text-xs">VS Code Copilot Simulator</span>
            </div>
            <h2 class="text-2xl font-extrabold text-white">Copilot Agent Sandbox Playground</h2>
            <p class="text-xs sm:text-sm text-[var(--text-secondary)]">Test how GitHub Copilot executes with custom agent instructions and knowledge base grounding.</p>
          </div>

          <!-- Select Agent Dropdown -->
          <div class="flex items-center gap-3">
            <select 
              onchange="window.InteractivePlayground.selectAgent(this.value)"
              class="input-field py-2 text-xs font-semibold"
            >
              ${agents.map(a => `
                <option value="${a.id}" ${a.id === activeAgent.id ? 'selected' : ''}>
                  ${a.name} (${a.copilotChatHandle})
                </option>
              `).join('')}
            </select>
          </div>
        </div>

        <!-- Playground Layout: Left Context Sidebar (4 cols) & Right Chat Interface (8 cols) -->
        <div class="grid grid-cols-1 lg:grid-cols-12 gap-6">
          
          <!-- Left: Injected Agent Context & KB Inspector -->
          <div class="lg:col-span-4 space-y-4">
            
            <!-- Agent Card Info -->
            <div class="glass-panel p-5 rounded-2xl border border-[var(--border-subtle)] space-y-3">
              <div class="flex items-center gap-3">
                <div class="w-10 h-10 rounded-xl flex items-center justify-center shadow" style="background: linear-gradient(135deg, ${activeAgent.color}33, ${activeAgent.color}11); border: 1px solid ${activeAgent.color}66;">
                  <i data-lucide="${activeAgent.icon || 'bot'}" class="w-5 h-5" style="color: ${activeAgent.color}"></i>
                </div>
                <div>
                  <h4 class="font-bold text-sm text-white">${activeAgent.name}</h4>
                  <div class="text-[11px] font-mono text-purple-300">${activeAgent.copilotChatHandle}</div>
                </div>
              </div>

              <div class="text-xs text-[var(--text-secondary)] leading-relaxed">
                ${activeAgent.tagline}
              </div>

              <div class="pt-2 border-t border-[var(--border-subtle)] space-y-2 text-xs">
                <div class="flex items-center justify-between text-[11px] text-[var(--text-muted)]">
                  <span>Knowledge Base Context:</span>
                  <span class="badge badge-amber text-[10px]">${kbCount} Documents Grounded</span>
                </div>
                <div class="flex items-center justify-between text-[11px] text-[var(--text-muted)]">
                  <span>Model Routing:</span>
                  <span class="text-cyan-300 font-semibold text-[10px]">${activeAgent.copilotModel}</span>
                </div>
              </div>
            </div>

            <!-- Injected System Instructions Preview -->
            <div class="glass-panel p-5 rounded-2xl border border-[var(--border-subtle)] space-y-2">
              <div class="text-xs font-bold uppercase tracking-wider text-purple-300 flex items-center justify-between">
                <span>Injected Copilot Rules</span>
                <span class="text-[10px] text-emerald-400 flex items-center gap-1"><i data-lucide="shield" class="w-3 h-3"></i> Active</span>
              </div>
              <pre class="code-block text-[11px] max-h-48 overflow-y-auto"><code>${this.escapeHtml(activeAgent.copilotConfig?.instructionsSnippet || '')}</code></pre>
            </div>

            <!-- Quick Sample Prompts -->
            <div class="glass-panel p-5 rounded-2xl border border-[var(--border-subtle)] space-y-2">
              <div class="text-xs font-bold uppercase tracking-wider text-[var(--text-muted)]">Quick Sample Prompts</div>
              <div class="space-y-1.5">
                <button onclick="window.InteractivePlayground.sendSampleQuery('${activeAgent.copilotChatHandle} diagnose pod crash in production cluster')" class="w-full text-left p-2 rounded-lg bg-[var(--bg-input)] hover:bg-[var(--bg-tertiary)] text-[11px] text-gray-300 border border-[var(--border-subtle)] transition-colors truncate">
                  ⚡ "${activeAgent.copilotChatHandle} diagnose pod crash in prod"
                </button>
                <button onclick="window.InteractivePlayground.sendSampleQuery('${activeAgent.copilotChatHandle} review code against OWASP standards')" class="w-full text-left p-2 rounded-lg bg-[var(--bg-input)] hover:bg-[var(--bg-tertiary)] text-[11px] text-gray-300 border border-[var(--border-subtle)] transition-colors truncate">
                  ⚡ "${activeAgent.copilotChatHandle} review code for security flaws"
                </button>
              </div>
            </div>

          </div>

          <!-- Right: Interactive Chat Terminal -->
          <div class="lg:col-span-8 glass-panel p-6 rounded-2xl border border-[var(--border-medium)] flex flex-col justify-between min-h-[580px] shadow-2xl">
            
            <!-- Terminal Header -->
            <div class="flex items-center justify-between border-b border-[var(--border-subtle)] pb-3 text-xs text-[var(--text-muted)]">
              <div class="flex items-center gap-2">
                <div class="flex gap-1">
                  <div class="w-2.5 h-2.5 rounded-full bg-rose-500"></div>
                  <div class="w-2.5 h-2.5 rounded-full bg-amber-500"></div>
                  <div class="w-2.5 h-2.5 rounded-full bg-emerald-500"></div>
                </div>
                <span class="font-mono text-white text-xs ml-1">Copilot Chat Session</span>
              </div>
              <div class="flex items-center gap-3">
                <button onclick="window.InteractivePlayground.state.chatHistory = []; window.InteractivePlayground.render();" class="text-gray-400 hover:text-white text-[11px] flex items-center gap-1">
                  <i data-lucide="trash-2" class="w-3.5 h-3.5"></i> Clear Chat
                </button>
              </div>
            </div>

            <!-- Chat Messages Scroll Container -->
            <div id="chat-messages-container" class="space-y-4 py-4 overflow-y-auto max-h-[420px] flex-1">
              ${this.state.chatHistory.length === 0 ? `
                <div class="text-center py-16 space-y-3">
                  <div class="w-12 h-12 rounded-2xl bg-purple-900/30 border border-purple-500/30 flex items-center justify-center mx-auto text-purple-400">
                    <i data-lucide="message-square" class="w-6 h-6"></i>
                  </div>
                  <h4 class="text-base font-bold text-white">Interactive Copilot Sandbox Ready</h4>
                  <p class="text-xs text-[var(--text-secondary)] max-w-sm mx-auto">
                    Type a prompt below or click a quick sample above to test execution with <strong class="text-purple-300">${activeAgent.name}</strong>.
                  </p>
                </div>
              ` : this.state.chatHistory.map(msg => this.renderMessage(msg, activeAgent)).join('')}
            </div>

            <!-- Input Bar -->
            <div class="pt-4 border-t border-[var(--border-subtle)]">
              <form onsubmit="event.preventDefault(); window.InteractivePlayground.handleSend();" class="flex items-center gap-2">
                <input 
                  type="text" 
                  id="playground-input"
                  placeholder="Ask ${activeAgent.copilotChatHandle} to diagnose, refactor, or test code..." 
                  class="input-field text-xs py-2.5 font-mono"
                  autofocus
                />
                <button type="submit" class="btn btn-primary text-xs py-2.5 px-4 flex items-center gap-1.5 shadow-md">
                  <span>Send</span>
                  <i data-lucide="send" class="w-3.5 h-3.5"></i>
                </button>
              </form>
            </div>

          </div>

        </div>

      </div>
    `;

    if (window.lucide) window.lucide.createIcons();
  },

  escapeHtml(text) {
    if (!text) return '';
    return text
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#039;");
  }
};
